title: Shayan's Blog Blog
description: "Class of 2028"
owner_name: Shayan Bhatti 
github_username: Shayanb1
github_repo: "Shayan-s-Page"
baseurl: "/Shayan-s-Page"
future: true
# remote_theme: jekyll/minima
minima:
  skin: dark
  social_link:
    - { platform: github, user_url: "https://https://github.com/Ruhaan-Bansal"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" }
# remote_theme: pages-themes/midnight@v0.2.0
remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/lessons.md
  - navigation/blog.md
  - navigation/search.md  
  - navigation/about.md
  - navigation/snake.md 
  - navigation/ideas.md
  - README4YML.md
  - navigation/spGame.md
include:
  - "*.ipynb"
